### ISSUE TITLE
Correct usage of initPlugin?

### ISSUE THREAD

**Issue by McGern** [255kb/cordova-plugin-bluetooth-status#3] opened 2015-11-23 10:04 UTC
Hi,

Running on ios 9.1, and after using initPlugin() in deviceReady the values are not yet populated correctly. If I query hasBTLE (for example) in the console it will return the correct value, or if I use a setTimeout (arbitrary time set to 0) it will also give the correct value.

Noticed in the code that initPlugin() is also waiting for deviceReady, which explains the setTimeout working, so was wondering where is the correct place to to call initPlugin?

Thanks,
Jarrod

**Comment by mrlowe** [comment] 2015-12-01 20:14
@McGern, I'm having a similar problem, but using a timeout doesn't seem to resolve it. When I check the value of isEnabled.get(), it's always false until I toggle bluetooth in settings. Then the value is updated correctly -- even if I kill the app and restart it -- until I reinstall or update the app, and then isEnabled is always false until I toggle it in settings again.

Does that look anything like your problem?

**Comment by 255kb** [comment] 2015-12-02 09:53
Hi, this issue seems to be a duplicate of #2. I will have a look into the issue asap.
Thanks

**Comment by McGern** [comment] 2015-12-02 09:59
I haven't had the issue with BT not being enabled,  but that just may be
because I haven't looked into it deeply enough. It sounds more like the
issue decided in the link below to #2

**Comment by 255kb** [comment] 2016-02-14 17:50
Should be solved in v1.0.4 see #2

**Closed as completed by 255kb** 2016-02-14 17:50 UTC
